import = ["~/.config/alacritty/rose-pine.toml"]
#[env]
#TERM = "xterm-256color"
[window]
opacity = 0.90
padding =  {x=5,y=5}
dynamic_padding = true
dimensions = {columns = 140, lines = 45}
position = { x = 200, y = 100}


[font]
normal = {family="FiraMono Nerd Font", style="Normal"}
size = 14

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#11111b"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen"}]

